import { TreeNode } from "./types";

export const initialTree: TreeNode = {
    id: "aircraft_system",
    name: "Aircraft System",
    type: "system",
    children: [
        {
            id: "propulsion_subsystem",
            name: "Propulsion Subsystem",
            type: "subsystem",
            children: [
                {
                    id: "engine",
                    name: "Engine",
                    type: "component",
                    children: [
                        {
                            id: "generate_thrust",
                            name: "Generate Thrust",
                            type: "function",
                            children: [
                                {
                                    id: "fuel_starvation",
                                    name: "Fuel Starvation",
                                    type: "fault",
                                    effect: "Loss of engine power",
                                    cause: "Fuel supply interruption",
                                    severity: 8,
                                    occurrence: 3,
                                    detection: 4,
                                    controls: "Fuel pressure monitoring",
                                },
                                {
                                    id: "compressor_failure",
                                    name: "Compressor Failure",
                                    type: "fault",
                                    effect: "Reduced engine performance",
                                    cause: "Foreign object damage",
                                    severity: 7,
                                    occurrence: 2,
                                    detection: 5,
                                    controls: "Regular inspections",
                                },
                            ],
                        },
                        {
                            id: "control_engine_speed",
                            name: "Control Engine Speed",
                            type: "function",
                            children: [
                                {
                                    id: "throttle_malfunction",
                                    name: "Throttle Malfunction",
                                    type: "fault",
                                    effect: "Uncontrolled engine speed",
                                    cause: "Faulty throttle sensor",
                                    severity: 6,
                                    occurrence: 2,
                                    detection: 3,
                                    controls: "Redundant sensors",
                                },
                            ],
                        },
                    ],
                },
                {
                    id: "fuel_system",
                    name: "Fuel System",
                    type: "component",
                    children: [
                        {
                            id: "store_fuel",
                            name: "Store Fuel",
                            type: "function",
                            children: [
                                {
                                    id: "fuel_tank_leak",
                                    name: "Fuel Tank Leak",
                                    type: "fault",
                                    effect: "Fuel loss during flight",
                                    cause: "Structural damage",
                                    severity: 9,
                                    occurrence: 1,
                                    detection: 6,
                                    controls: "Regular tank inspections",
                                },
                            ],
                        },
                        {
                            id: "refuel_aircraft",
                            name: "Refuel Aircraft",
                            type: "function",
                            children: [
                                {
                                    id: "fuel_spill",
                                    name: "Fuel Spill",
                                    type: "fault",
                                    effect: "Environmental hazard",
                                    cause: "Improper refueling procedures",
                                    severity: 5,
                                    occurrence: 3,
                                    detection: 4,
                                    controls: "Training and monitoring",
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        {
            id: "electrical_subsystem",
            name: "Electrical Subsystem",
            type: "subsystem",
            children: [
                {
                    id: "battery",
                    name: "Battery",
                    type: "component",
                    children: [
                        {
                            id: "provide_electrical_power",
                            name: "Provide Electrical Power",
                            type: "function",
                            children: [
                                {
                                    id: "battery_depletion",
                                    name: "Battery Depletion",
                                    type: "fault",
                                    effect: "Loss of electrical power",
                                    cause: "Excessive power draw",
                                    severity: 5,
                                    occurrence: 4,
                                    detection: 2,
                                    controls: "Battery charge monitoring",
                                },
                                {
                                    id: "short_circuit",
                                    name: "Short Circuit",
                                    type: "fault",
                                    effect: "Electrical system failure",
                                    cause: "Insulation breakdown",
                                    severity: 8,
                                    occurrence: 2,
                                    detection: 3,
                                    controls: "Circuit breakers",
                                },
                            ],
                        },
                    ],
                },
                {
                    id: "generator",
                    name: "Generator",
                    type: "component",
                    children: [
                        {
                            id: "generate_electricity",
                            name: "Generate Electricity",
                            type: "function",
                            children: [
                                {
                                    id: "generator_overheating",
                                    name: "Overheating",
                                    type: "fault",
                                    effect: "Generator shutdown",
                                    cause: "Cooling system failure",
                                    severity: 10,
                                    occurrence: 10,
                                    detection: 9,
                                    controls: "Temperature sensors",
                                },
                                {
                                    id: "voltage_fluctuation",
                                    name: "Voltage Fluctuation",
                                    type: "fault",
                                    effect: "Inconsistent power supply",
                                    cause: "Load changes",
                                    severity: 7,
                                    occurrence: 5,
                                    detection: 4,
                                    controls: "Voltage regulators",
                                },
                            ],
                        },
                    ],
                },
            ],
        },
        {
            id: "avionics_subsystem",
            name: "Avionics Subsystem",
            type: "subsystem",
            children: [
                {
                    id: "navigation_system",
                    name: "Navigation System",
                    type: "component",
                    children: [
                        {
                            id: "provide_navigation_data",
                            name: "Provide Navigation Data",
                            type: "function",
                            children: [
                                {
                                    id: "gps_failure",
                                    name: "GPS Failure",
                                    type: "fault",
                                    effect: "Loss of accurate position data",
                                    cause: "Satellite signal interference",
                                    severity: 6,
                                    occurrence: 3,
                                    detection: 4,
                                    controls: "Redundant navigation systems",
                                },
                                {
                                    id: "navigation_software_error",
                                    name: "Navigation Software Error",
                                    type: "fault",
                                    effect: "Incorrect navigation data",
                                    cause: "Software bug",
                                    severity: 7,
                                    occurrence: 2,
                                    detection: 5,
                                    controls: "Regular software updates",
                                },
                            ],
                        },
                    ],
                },

                {
                    id: "system_health_monitoring",
                    name: "System Health Monitoring",
                    type: "function",
                    children: [
                        {
                            id: "sensor_failure",
                            name: "Sensor Failure",
                            type: "fault",
                            effect: "Inaccurate health data",
                            cause: "Sensor malfunction",
                            severity: 5,
                            occurrence: 3,
                            detection: 4,
                            controls: "Regular sensor calibration",
                        },
                        {
                            id: "data_processing_error",
                            name: "Data Processing Error",
                            type: "fault",
                            effect: "Delayed health status updates",
                            cause: "Software glitch",
                            severity: 4,
                            occurrence: 2,
                            detection: 3,
                            controls: "Error handling protocols",
                        },
                    ],
                },
            ],
        },
        {
            id: "fuel_efficiency_monitoring",
            name: "Fuel Efficiency Monitoring",
            type: "function",
            children: [
                {
                    id: "fuel_leak_detection",
                    name: "Fuel Leak Detection",
                    type: "fault",
                    effect: "Loss of fuel efficiency",
                    cause: "Leak in fuel lines",
                    severity: 6,
                    occurrence: 3,
                    detection: 4,
                    controls: "Regular inspections and monitoring systems",
                },
                {
                    id: "engine_tuning_issue",
                    name: "Engine Tuning Issue",
                    type: "fault",
                    effect: "Suboptimal fuel consumption",
                    cause: "Improper engine calibration",
                    severity: 5,
                    occurrence: 2,
                    detection: 3,
                    controls: "Routine engine tuning and diagnostics",
                },
            ],
        },
    ],
};
